#!/bin/bash
export LD_LIBRARY_PATH=/opt/boost/lib:/opt/sdx_runtime/runtime/lib/x86_64:/opt/sdx_runtime/opencv:$LD_LIBRARY_PATH

#/opt/gemx/out_host/gemx_api_gemm.exe /opt/gemx/xclbins/gemm_perf_vcu1525.xclbin 512 512 512 512 512 512 512 1 0 A B C X

echo "Please enter the application name (gemm_perf, spmv_perf or gemm_test_python):"
read app_name

if [ $app_name = "gemm_perf" ]; then
  echo "Please enter size of dimension M, K and N. Note M, K and N must be multiple of 128"
  read M, N, K
  #/opt/gemx/out_host/gemx_api_gemm.exe /opt/gemx/xclbins/gemm_perf_vcu1525.xclbin 512 512 512 512 512 512 512 1 0 A B C X
  /opt/gemx/out_host/gemx_api_gemm.exe /opt/gemx/xclbins/gemm_perf_vcu1525.xclbin $M $N $K $K $N $N $N 1 0 A B C X
elif [ $app_name = "spmv_perf" ]; then 
  read -p "Please enter the sparse matrix name: "
  read spm_name
  #/opt/gemx/out_host/gemx_api_spmv.exe /opt/gemx/xclbins/spmv_perf_vcu1525.xclbin 0 0 0 /opt/gemx/data/spmv/Rucci1.mtx.gz 
/opt/gemx/out_host/gemx_api_spmv.exe /opt/gemx/xclbins/spmv_perf_vcu1525.xclbin 0 0 0 $spm_name 
elif [ $app_name = "gemm_test_python" ]; then
python /opt/gemx/src/python/test_gemm.py --xclbin /opt/gemx/xclbins/gemm_perf_vcu1525.xclbin --gemxlib /opt/gemx/out_host/lib/libgemxhost.so 
else
 echo "invalid application name."
fi
exit
